services:
  massolit:
    image: ghcr.io/veritymedia/massolit:latest
    volumes:
      - massolit_data:/app/pb_data
    environment:
      MANAGEBAC_API: ${MANAGEBAC_API}
    ports:
      - 8091:8090
    networks:
      - dokploy-network
volumes:
  massolit_data:

networks:
  dokloy-network:
